export const categories = [
  {
    name: "Dispensary Drugs",
    value: "Dispensary Drugs",
  },
  {
    name: "Cardiovascular drugs",
    value: "category-2",
  },
  {
    name: "AntiInfectives",
    value: "category-3",
  },
  {
    name: "NSAIDs",
    value: "category-4",
  },
  {
    name: "Antiretrovirals",
    value: "category-5",
  },
  {
    name: "Endocrine and Metabollic Drugs",
    value: "category-5",
  },
  {
    name: "CNS Drugs",
    value: "category-5",
  },
  {
    name: "Respiratory Drugs",
    value: "category-5",
  },
  {
    name: "GastroIntestinal Drugs",
    value: "category-5",
  },
  {
    name: "Hematologic Drugs",
    value: "category-5",
  },
  {
    name: "Opthalmic ,ENT and Dermatological",
    value: "category-5",
  },
];

export const composites = [
  {
    name: "Ceramics",
    value: "ceramics",
  },
  {
    name: "Cotton",
    value: "cotton",
  },
  {
    name: "Matt Paper",
    value: "matt-paper",
  },
  {
    name: "Polyester",
    value: "polyester",
  },
  {
    name: "Recycled Paper",
    value: "recycled-paper",
  },
];

export const dummyorders: IOrder[] = [
  {
    id: "ORD-001",
    customerName: "John Doe",
    customerEmail: "john.doe@example.com",
    date: "2024-10-15T10:30:00Z",
    items: [
      {
        productId: "1",
        name: "Joint Support Complex",
        image: "/demo/image1.jpg",
        price: 20.01,
        quantity: 2,
        subtotal: 40.02,
        discount: 31,
      },
      {
        productId: "3",
        name: "Vitamin D3 5000 IU",
        image: "/demo/image2.png",
        price: 13.99,
        quantity: 1,
        subtotal: 13.99,
        discount: 30,
      },
    ],
    subtotal: 54.01,
    tax: 5.4,
    shipping: 7.99,
    total: 67.4,
    status: "completed",
    paymentMethod: "credit card",
    paymentStatus: "paid",
    shippingAddress: {
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
    },
    trackingNumber: "TRK123456789",
    createdAt: "2024-10-15T10:30:00Z",
    updatedAt: "2024-10-16T14:20:00Z",
  },
  {
    id: "ORD-002",
    customerName: "Jane Smith",
    customerEmail: "jane.smith@example.com",
    date: "2024-10-16T14:22:00Z",
    items: [
      {
        productId: "5",
        name: "Collagen Peptides Powder",
        image: "/demo/image1.jpg",
        price: 27.99,
        quantity: 3,
        subtotal: 83.97,
        discount: 30,
      },
    ],
    subtotal: 83.97,
    tax: 8.4,
    shipping: 0.0,
    total: 92.37,
    status: "processing",
    paymentMethod: "paypal",
    paymentStatus: "paid",
    shippingAddress: {
      street: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      country: "USA",
    },
    trackingNumber: "TRK987654321",
    createdAt: "2024-10-16T14:22:00Z",
    updatedAt: "2024-10-16T15:10:00Z",
  },
  {
    id: "ORD-003",
    customerName: "Michael Brown",
    customerEmail: "michael.brown@example.com",
    date: "2024-10-17T09:15:00Z",
    items: [
      {
        productId: "2",
        name: "Omega 3 Fish Oil Softgels",
        image: "/demo/image1.png",
        price: 18.5,
        quantity: 1,
        subtotal: 18.5,
        discount: 29,
      },
      {
        productId: "4",
        name: "Magnesium Glycinate Capsules",
        image: "/demo/image1.jpg",
        price: 19.59,
        quantity: 2,
        subtotal: 39.18,
        discount: 30,
      },
    ],
    subtotal: 57.68,
    tax: 5.77,
    shipping: 7.99,
    total: 71.44,
    status: "pending",
    paymentMethod: "debit card",
    paymentStatus: "unpaid",
    shippingAddress: {
      street: "789 Pine Road",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      country: "USA",
    },
    createdAt: "2024-10-17T09:15:00Z",
    updatedAt: "2024-10-17T09:15:00Z",
  },
  {
    id: "ORD-004",
    customerName: "Emily Davis",
    customerEmail: "emily.davis@example.com",
    date: "2024-10-14T16:45:00Z",
    items: [
      {
        productId: "1",
        name: "Joint Support Complex",
        image: "/demo/image1.jpg",
        price: 20.01,
        quantity: 1,
        subtotal: 20.01,
        discount: 31,
      },
      {
        productId: "2",
        name: "Omega 3 Fish Oil Softgels",
        image: "/demo/image1.png",
        price: 18.5,
        quantity: 1,
        subtotal: 18.5,
        discount: 29,
      },
      {
        productId: "3",
        name: "Vitamin D3 5000 IU",
        image: "/demo/image2.png",
        price: 13.99,
        quantity: 2,
        subtotal: 27.98,
        discount: 30,
      },
    ],
    subtotal: 66.49,
    tax: 6.65,
    shipping: 7.99,
    total: 81.13,
    status: "completed",
    paymentMethod: "credit card",
    paymentStatus: "paid",
    shippingAddress: {
      street: "321 Elm Street",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
      country: "USA",
    },
    trackingNumber: "TRK456789123",
    createdAt: "2024-10-14T16:45:00Z",
    updatedAt: "2024-10-15T11:30:00Z",
  },
  {
    id: "ORD-005",
    customerName: "David Wilson",
    customerEmail: "david.wilson@example.com",
    date: "2024-10-13T11:20:00Z",
    items: [
      {
        productId: "4",
        name: "Magnesium Glycinate Capsules",
        image: "/demo/image1.jpg",
        price: 19.59,
        quantity: 1,
        subtotal: 19.59,
        discount: 30,
      },
    ],
    subtotal: 19.59,
    tax: 1.96,
    shipping: 7.99,
    total: 29.54,
    status: "cancelled",
    paymentMethod: "cash on delivery",
    paymentStatus: "refunded",
    shippingAddress: {
      street: "654 Maple Drive",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
      country: "USA",
    },
    notes: "Customer requested cancellation due to change of mind",
    createdAt: "2024-10-13T11:20:00Z",
    updatedAt: "2024-10-14T09:00:00Z",
  },
  {
    id: "ORD-006",
    customerName: "Sarah Johnson",
    customerEmail: "sarah.johnson@example.com",
    date: "2024-10-18T08:30:00Z",
    items: [
      {
        productId: "5",
        name: "Collagen Peptides Powder",
        image: "/demo/image1.jpg",
        price: 27.99,
        quantity: 2,
        subtotal: 55.98,
        discount: 30,
      },
      {
        productId: "3",
        name: "Vitamin D3 5000 IU",
        image: "/demo/image2.png",
        price: 13.99,
        quantity: 3,
        subtotal: 41.97,
        discount: 30,
      },
    ],
    subtotal: 97.95,
    tax: 9.8,
    shipping: 0.0,
    total: 107.75,
    status: "processing",
    paymentMethod: "paypal",
    paymentStatus: "paid",
    shippingAddress: {
      street: "987 Cedar Lane",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19019",
      country: "USA",
    },
    trackingNumber: "TRK789123456",
    createdAt: "2024-10-18T08:30:00Z",
    updatedAt: "2024-10-18T10:15:00Z",
  },
  {
    id: "ORD-007",
    customerName: "Robert Martinez",
    customerEmail: "robert.martinez@example.com",
    date: "2024-10-12T13:50:00Z",
    items: [
      {
        productId: "2",
        name: "Omega 3 Fish Oil Softgels",
        image: "/demo/image1.png",
        price: 18.5,
        quantity: 4,
        subtotal: 74.0,
        discount: 29,
      },
    ],
    subtotal: 74.0,
    tax: 7.4,
    shipping: 7.99,
    total: 89.39,
    status: "completed",
    paymentMethod: "credit card",
    paymentStatus: "paid",
    shippingAddress: {
      street: "147 Birch Court",
      city: "San Antonio",
      state: "TX",
      zipCode: "78201",
      country: "USA",
    },
    trackingNumber: "TRK321654987",
    createdAt: "2024-10-12T13:50:00Z",
    updatedAt: "2024-10-13T16:20:00Z",
  },
  {
    id: "ORD-008",
    customerName: "Lisa Anderson",
    customerEmail: "lisa.anderson@example.com",
    date: "2024-10-17T15:10:00Z",
    items: [
      {
        productId: "1",
        name: "Joint Support Complex",
        image: "/demo/image1.jpg",
        price: 20.01,
        quantity: 3,
        subtotal: 60.03,
        discount: 31,
      },
      {
        productId: "4",
        name: "Magnesium Glycinate Capsules",
        image: "/demo/image1.jpg",
        price: 19.59,
        quantity: 1,
        subtotal: 19.59,
        discount: 30,
      },
    ],
    subtotal: 79.62,
    tax: 7.96,
    shipping: 7.99,
    total: 95.57,
    status: "pending",
    paymentMethod: "debit card",
    paymentStatus: "paid",
    shippingAddress: {
      street: "258 Willow Street",
      city: "San Diego",
      state: "CA",
      zipCode: "92101",
      country: "USA",
    },
    createdAt: "2024-10-17T15:10:00Z",
    updatedAt: "2024-10-17T15:10:00Z",
  },
  {
    id: "ORD-009",
    customerName: "James Taylor",
    customerEmail: "james.taylor@example.com",
    date: "2024-10-16T12:00:00Z",
    items: [
      {
        productId: "5",
        name: "Collagen Peptides Powder",
        image: "/demo/image1.jpg",
        price: 27.99,
        quantity: 1,
        subtotal: 27.99,
        discount: 30,
      },
      {
        productId: "2",
        name: "Omega 3 Fish Oil Softgels",
        image: "/demo/image1.png",
        price: 18.5,
        quantity: 2,
        subtotal: 37.0,
        discount: 29,
      },
    ],
    subtotal: 64.99,
    tax: 6.5,
    shipping: 7.99,
    total: 79.48,
    status: "completed",
    paymentMethod: "credit card",
    paymentStatus: "paid",
    shippingAddress: {
      street: "369 Spruce Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      country: "USA",
    },
    trackingNumber: "TRK654321789",
    createdAt: "2024-10-16T12:00:00Z",
    updatedAt: "2024-10-17T09:45:00Z",
  },
  {
    id: "ORD-010",
    customerName: "Patricia White",
    customerEmail: "patricia.white@example.com",
    date: "2024-10-18T10:25:00Z",
    items: [
      {
        productId: "3",
        name: "Vitamin D3 5000 IU",
        image: "/demo/image2.png",
        price: 13.99,
        quantity: 5,
        subtotal: 69.95,
        discount: 30,
      },
    ],
    subtotal: 69.95,
    tax: 7.0,
    shipping: 0.0,
    total: 76.95,
    status: "processing",
    paymentMethod: "paypal",
    paymentStatus: "paid",
    shippingAddress: {
      street: "741 Ash Boulevard",
      city: "San Jose",
      state: "CA",
      zipCode: "95101",
      country: "USA",
    },
    trackingNumber: "TRK147258369",
    createdAt: "2024-10-18T10:25:00Z",
    updatedAt: "2024-10-18T11:00:00Z",
  },
];

export const posts: IBlogPost[] = [
  {
    id: 1,
    title: "Nullam ullamcorper nisl quis ornare molestie",
    author: "Demo Demo",
    category: "Sub Category 1",
    date: "Wednesday February 1 2023",
    comments: 0,
    hits: 1811,
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop",
    excerpt:
      "Suspendisse posuere, diam in bibendum lobortis, turpis ipsum aliquam risus, sit amet dictum ligula lorem non nisl. Urna pretium elit mauris cursus Curabitur ut elit. Vestibulum sed ut erat volutpat...",
  },
  {
    id: 2,
    title: "Etiam eget erat est Phasellus elit justo",
    author: "John Smith",
    category: "Sub Category 2",
    date: "Tuesday January 31 2023",
    comments: 5,
    hits: 2340,
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop",
    excerpt:
      "Mattis non lorem aliquam aliquam leo. Sed fermentum consectetur magna, eget semper ante. Aliquam scelerisque justo velit. Fusce cursus blandit dolor, in sodales urna vulputate lobortis...",
  },
  {
    id: 3,
    title: "Vivamus mattis volutpat erat et congue",
    author: "Sarah Johnson",
    category: "Sub Category 3",
    date: "Monday January 30 2023",
    comments: 12,
    hits: 3102,
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop",
    excerpt:
      "Curabitur faucibus aliquam pulvinar. Nulla ut tellus turpis. Nullam lacus sem, volutpat id odio sed, cursus tristique eros. Duis at pellentesque magna. Donec magna nisl...",
  },
  {
    id: 4,
    title: "Curabitur dignissim bibend in aliquip enim",
    author: "Mike Chen",
    category: "Sub Category 1",
    date: "Sunday January 29 2023",
    comments: 8,
    hits: 1567,
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop",
    excerpt:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur faucibus aliquam pulvinar. Vivamus mattis volutpat erat...",
  },
  {
    id: 5,
    title: "Nulla id pharetra dui at rhoncus urn",
    author: "Emma Wilson",
    category: "Sub Category 2",
    date: "Saturday January 28 2023",
    comments: 3,
    hits: 892,
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop",
    excerpt:
      "Maecenas non porttitor purus. Nullam ullamcorper nisl quis ornare molestie. Etiam eget erat est. Phasellus elit justo, mattis non lorem non, aliquam aliquam leo...",
  },
];
